name: Github CI

env:
  HOPR_GITHUB_REF: ${{ github.ref }}

on:
  push:
    branches: ["ci"]

jobs:
  docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: ./yarn.lock
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        shell: bash
        run: yarn

      - name: Configure Git info
        run: ./.github/scripts/config-git-info.sh

      - name: Create docs
        run: yarn docs

      - name: Commit docs changes
        # only commit changes when not running via act and when on final branches
        # if: |
        #   (github.ref == 'refs/heads/master' ||
        #    github.ref == 'refs/heads/avado' ||
        #    startsWith(github.ref, 'refs/heads/debug-docs/') ||
        #    startsWith(github.ref, 'refs/heads/release/')
        #   ) && !env.ACT
        run: ./.github/scripts/commit-and-push-all-changes.sh
        env:
          HOPR_GIT_MSG: "Re-generate API docs for packages"
